### ISSUE TITLE
uclcmd segfaults when including an empty file

### ISSUE THREAD

**Issue by Crest** [allanjude/uclcmd#18]
The uclcmd program crashes with a segfault when including an empty file on FreeBSD 10.3. I suspect this a side effect of how FreeBSD handles mmap() calls with a length of zero (afaik it returns NULL which isn't the same as MAP_FAILED).

**Comment by allanjude** [comment]
This was fixed upstream in libucl:

https://github.com/vstakhov/libucl/commit/0c24799829f2252440ac5975d59599e78b6e4a0b
https://github.com/vstakhov/libucl/commit/8dc8b443f10555f90478666a289a32638bb269b9
