### ISSUE TITLE
uclcmd segfaults

### ISSUE THREAD

**Issue by dch** [allanjude/uclcmd#21]
I just ran into this while using `uclcmd` to generate `pkg-create(8)` manifests from ucl fragments.. Various case sensitivity tests cause `SIGSEGV`:

I'd expect the following snippet to be parsed as `key: [value, Value]` if we are case insensitive, and separately if we are case aware.

Built off `FreeBSD 12.0-CURRENT 
FreeBSD akai.skunkwerks.at 12.0-CURRENT FreeBSD 12.0-CURRENT #0 r311461: Thu Jan  5 22:46:38 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64`

```yaml
# test.ucl 
key: value
Key: Value
KEYS: ValueS
```

```sh
 /t/ucl uclcmd get --yaml --keys --file test.ucl .keys
"ValueS"
 /t/ucl uclcmd get --yaml --keys --file test.ucl .KEYS
fish: “uclcmd get --yaml --keys --file…” terminated by signal SIGSEGV (Address boundary error)
 /t/ucl uclcmd get --yaml --keys --file test.ucl .KEY                                                                                                                                                (139) 
fish: “uclcmd get --yaml --keys --file…” terminated by signal SIGSEGV (Address boundary error)
 /t/ucl uclcmd get --yaml --keys --file test.ucl .key
[
    "value",
    "Value"
]
 /t/ucl uclcmd get --json --keys --file test.ucl .KEY
fish: “uclcmd get --json --keys --file…” terminated by signal SIGSEGV (Address boundary error)
 /t/ucl uclcmd get  --keys --file test.ucl .KEY                                                                                                                                                      (139) 
KEY=null
 /t/ucl uclcmd get  --keys --file test.ucl .key
key=[array]
 /t/ucl uclcmd get --json --keys --file test.ucl .key
[
    "value",
    "Value"
]
 /t/ucl uclcmd get --yaml --keys --file test.ucl .key
[
    "value",
    "Value"
]
 /t/ucl 
```

**Comment by allanjude** [comment]
Would you have time to re-test this after 2bc8997a96983dad6b0c364a9a83290cc29765c3 ?

**Comment by dch** [comment]
my pleasure!

- [x] no more segfaults (even since 0.1_3 from ports)

It's clear to me why the parser folds key case, from reading
the code, but its not common in JSON nor YAML to do so.
If there's a good reason for this then that's worth explaining
why. Does it happen elsewhere in FreeBSD config files?

PR coming with a test for the folding result.

**Comment by dch** [comment]
https://github.com/allanjude/uclcmd/pull/27
