### ISSUE TITLE
Data type handling could be improved.

### ISSUE THREAD

**Issue by ethoms** [allanjude/uclcmd#22]
Hi, firstly, thanks for uclmd. It has become a big part of a FreeBSD specific server management framework I'm developing. Working with configuration files for my shell based utility scripts is now really great, especially when it comes to using arrays.

I only just noticed a bug in my project, due to a ``set`` command not doing what I expected. When I try to set a key value pair with alphanumeric value starting with numbers it sets the value to a long number. I'm asuming ``uclcmd`` thinks that becuase it starts with a number, it must be a number, and something like ``atoa`` is returning a large integer.

**Command used:** 

```
# uclcmd set -f test.conf name "100GB"
```

**Expected result:**

```
# cat test.conf 
name = "100GB";
```

**Actual result:**

```
# cat test.conf 
name = 107374182400;
```

I did notice that if I use the ``-t string`` argument to specify data type as string it works. I will now need to go and refactor all my code to specify the data type. Documentation seems a bit lacking for uclcmd, I had to guess the "string" and "number" data types, which seem to work. I couldn't find anywhere that the data-types are listed, yet I knew about the "array" and "object" data types from somewhere. Maybe I forgot where to look for help using uclcmd.

I can work on the data type detection logic when I get a bit more time. Would you be OK with my submitting a pull request for this if I find time to spend on it?

**Comment by allanjude** [comment]
In this case, I think you are actually jump bumping into the syntax sugar of UCL.
Where '100k' in the UCL file is expanded into 100,000 when parsing the file, and 100kb becomes 102,400

If it was just atoi type thing, it'd stop at the G, and the value would just be 100.

However, we might not actually want to apply the UCL parser to set always, as we do now (this is so you can set a key to have a value of an array). You might want a flag or something to mean 'literally this string'.

Interesting problem, I'll have to think about it.

**Comment by ethoms** [comment]
I didn't realise UCL did that kind of expansion so I never thought about that possibility. In that case maybe the parser should only look for valid suffixes to parse the expansion, otherwise treat it as a string.

The original string I encountered this issue was actually a file path offset ('100GB_GPT_NTFS/100GB_GPT_NTFS.img'). 

Perhaps the parser could just test for valid suffixes (k|K|m|M|g|G).

Anyways, I have already refactored my code to always specify the data type. Coming from a C/C++/Java background I prefer static typing anyway. For booleans, it may be particularly important to be clear about the data type.

**Comment by ethoms** [comment]
I think I'd better make this issue more clear with my original use case , instead of the simplified made up example.

**Command used:**

```
touch test.conf
uclcmd set -f test.conf name "100GB_GPT_NTFS/100GB_GPT_NTFS.img"
```

**Expected result:**

```
# cat test.conf 
name = "100GB_GPT_NTFS/100GB_GPT_NTFS.img";
```

**Actual result:**

```
# cat test.conf 
name = 107374182400;
```

**Comment by allanjude** [comment]
This problem is actually in the upstream libucl library. I have proposed a pull request to fix it: https://github.com/vstakhov/libucl/pull/259

**Comment by allanjude** [comment]
This is fixed upstream, and will be in the next release of libucl
